version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: swifttok-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: swifttok
      POSTGRES_PASSWORD: swifttok
      POSTGRES_DB: swifttok
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
